class ProductPage:
    """
The file contains locators for the product page
    """
    breadcrumb = ".//*[@class='breadcrumb']"
    product_images = ".//*[@class='thumbnails']"
    alert_line = ".//*[contains(@class, 'alert')]"
    wishlist_button = ".//*[contains(@class, 'fa-heart')]/ancestor::*[@class='btn btn-default']"
    compare_button = ".//*[contains(@class, 'fa-exchange')]/ancestor::*[@class='btn btn-default']"
    quantity_input = "input-quantity"
    add_to_card_button = "button-cart"
    share_buttons = "addthis_toolbox addthis_default_style"
    description_button = ".//*[@class='nav nav-tabs']//*[text()='Description']"
    description_active_button = description_button + "/ancestor::li[@class='active']"
    description_block = "tab-description"
    review_button = ".//*[@class='nav nav-tabs']//*[contains(text(),'Reviews')]"
    review_active_button = review_button + "/ancestor::li[@class='active']"
    review_block = "form-review"
    review_input_name = "input-name"
    review_input_review = "input-review"
    review_input_rating = ".//*[@name='rating'][@value='5']"
    review_continue_button = "button-review"
